blog/urls.py
from django.urls import path

from . import views
from .views import PostsView, ShowPost, CreatePost, CategoryView, RegisterUser, LoginUser, logout_user


app_name = 'blog'
urlpatterns = [
    path('', PostsView.as_view(), name='index'),
    path('create', CreatePost.as_view(), name='create_post'),
    path('post/<slug:post_slug>', ShowPost.as_view(), name='show_post'),
    path('cat/<slug:cat_slug>', CategoryView.as_view(), name='show_cat'),
    path('register', RegisterUser.as_view(), name='register'),
    path('login', LoginUser.as_view(), name='login'),
    path('logout', logout_user, name='logout'),
]

shop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('website.urls')),
    path('blog/', include('blog.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.urls import reverse
from django.utils.text import slugify
from unidecode import unidecode

from django.db import models


# Create your models here.
class PostModel(models.Model):
    author = models.CharField('Автор статьи', max_length=30)
    title = models.CharField('Название статьи', max_length=50)
    slug = models.SlugField('URL', max_length=60, unique=True, db_index=True, null=True, blank=True)
    text = models.TextField('Текст статьи')
    image = models.ImageField('Картинка к посту', upload_to='img')  # pillow
    publish_date = models.DateTimeField('Время публикации', auto_now=True)
    is_published = models.BooleanField('Пост опубликован?', default=True)
    category = models.ForeignKey('Category', on_delete=models.PROTECT, verbose_name='Категория')

    def get_absolute_url(self):
        return reverse('blog:show_post', kwargs={'post_slug': self.slug})

    def save(self, *args, **kwargs):
        if not self.slug:
            string = str(self.title)
            self.slug = slugify(unidecode(string))
        return super().save(*args, **kwargs)

    def __str__(self):
        return self.title

    class Meta:
        ordering = ['title']


# статья -> statia
class Category(models.Model):
    name = models.CharField('Категория', max_length=30, unique=True)
    slug = models.SlugField('URL', max_length=30, unique=True, db_index=True)

    def get_absolute_url(self):
        return reverse('blog:show_cat', kwargs={'cat_slug': self.slug})

    def __str__(self):
        return self.name

blog/forms.py
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User
from django.forms import ModelForm, TextInput, Textarea, SlugField, PasswordInput, CharField

from .models import PostModel


# Class Based Forms (CBF)
class PostForm(ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['author'].label = 'Автор статьи'
        self.fields['title'].label = 'Название статьи'
        self.fields['text'].label = 'Текст статьи'
        self.fields['slug'].label = 'URL статьи'
        self.label_suffix = ""
        self.fields['category'].empty_label = 'Категория не выбрана'

    class Meta:
        model = PostModel
        fields = ['author', 'title', 'slug', 'text', 'image', 'category']
        widgets = {
            'author': TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Введите автора статьи',
                'id': 'author-input'
            }),
            'title': TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Введите название статьи',
                'id': 'title-input'
            }),
            'text': Textarea(attrs={
                'class': 'form-control',
                'placeholder': 'Введите текст статьи',
                'id': 'text-input'
            }),
            'slug': TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Введите URL статьи (необязательно)',
                'id': 'slug-input'
            })
        }

    def clean_title(self):
        title = self.cleaned_data['title']
        if len(title) > 50:
            self.add_error('title', 'Больше 50 символов!')
        if '!!' in title:
            self.add_error('title', 'Очень много восклицательных знаков!!!')
        return title


class RegisterUserForm(UserCreationForm):
    username = CharField(label='Логин', widget=TextInput(attrs={'class': 'form-control', 'placeholder': 'Логин', 'id': 'login-input'}))
    password1 = CharField(label='Пароль', widget=PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Пароль', 'id': 'password1-input'}))
    password2 = CharField(label='Подтверждение пароля', widget=PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Подтверждение пароля', 'id': 'password2-input'}))

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.label_suffix = ''

    class Meta:
        model = User
        fields = ['username', 'password1', 'password2']


class LoginUserForm(AuthenticationForm):
    username = CharField(label='Логин', widget=TextInput(attrs={'class': 'form-control', 'placeholder': 'Логин', 'id': 'login-input'}))
    password = CharField(label='Пароль', widget=PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Пароль', 'id': 'password-input'}))

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.label_suffix = ''

    class Meta:
        model = User
        fields = ['username', 'password']

blog/views.py
from django.contrib.auth import logout
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.views import LoginView
from django.shortcuts import render, redirect
from django.views.generic import ListView, DetailView, CreateView, DeleteView
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin

from .models import PostModel, Category
from .forms import PostForm, RegisterUserForm, LoginUserForm
from .utils import DataMixin


class PostsView(DataMixin, ListView):
    model = PostModel
    template_name = 'blog/index.html'
    context_object_name = 'posts'
    # extra_context = {'title': 'Главная страница'}

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        # user_context = self.get_user_context(title='Главная страница')
        # context.update(user_context)
        context |= self.get_user_context(title='Главная страница')
        return context

    def get_queryset(self):
        return PostModel.objects.filter(is_published=True)


class CategoryView(DataMixin, ListView):
    model = PostModel
    template_name = 'blog/index.html'
    context_object_name = 'posts'
    # extra_context = {'title': 'Главная страница'}
    allow_empty = False

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context |= self.get_user_context(title=f'Категория {context["posts"][0].category.name}')
        return context

    def get_queryset(self):
        return PostModel.objects.filter(category__slug=self.kwargs['cat_slug'])


# Slug
class ShowPost(DataMixin, DetailView):
    model = PostModel
    template_name = 'blog/show_post.html'
    slug_url_kwarg = 'post_slug'
    context_object_name = 'post'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context |= self.get_user_context(title=context["post"].title)
        return context


class CreatePost(LoginRequiredMixin, DataMixin, CreateView):
    form_class = PostForm
    template_name = 'blog/create.html'
    raise_exception = False
    login_url = reverse_lazy('blog:login')
    success_url = reverse_lazy('blog:create_post')

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context |= self.get_user_context(title='Создание поста')
        return context


class RegisterUser(DataMixin, CreateView):
    form_class = RegisterUserForm
    template_name = 'blog/register.html'
    success_url = reverse_lazy('blog:index')

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context |= self.get_user_context(title='Регистрация')
        return context


class LoginUser(DataMixin, LoginView):
    form_class = LoginUserForm
    template_name = 'blog/login.html'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context |= self.get_user_context(title='Вход на сайт')
        return context

    def get_success_url(self):
        return reverse_lazy('blog:index')


def logout_user(request):
    logout(request)
    return redirect('blog:index')


class UserProfile:
    pass

blog/templates/blog/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% block title %}{% endblock %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>

<header>
    <div class="collapse bg-dark" id="navbarHeader">
        <div class="container">
            <div class="row">
                <div class="col-sm">
                    <h4 class="text-white">О нас</h4>
                    <p class="text-muted">Блог обо мне и о мире вокруг.</p>
                </div>
                <div class="col-sm">
                    <h4 class="text-white">Категории</h4>
                    <ul class="list-unstyled">
                        {% for cat in cats %}
                        <li><a href="{% url 'blog:show_cat' cat.slug %}" class="text-white">{{ cat.name }}</a></li>
                        {% empty %}
                        <p class="text-muted">Нет ни одной категории</p>
                        {% endfor %}
                    </ul>
                </div>
                <div class="col-sm">
                    <h4 class="text-white">Навигация</h4>
                    <ul class="list-unstyled">
                        <li><a href="{% url 'blog:index' %}" class="text-white">Главная</a></li>
                        {% if request.user.is_authenticated %}
                        <li><a href="{% url 'blog:create_post' %}" class="text-white">Создать пост</a></li>
                        {% endif %}
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <div class="navbar navbar-dark bg-dark shadow-sm">
        <div class="container">
            <div class="d-flex justify-content-start">
                <a href="{% url 'blog:index' %}" class="navbar-brand d-flex align-items-center">
                    <strong>Главная</strong>
                </a>
            </div>
            <div class="d-flex justify-content-end">
                {% if request.user.is_authenticated %}
                    <strong class="navbar-brand">{{ user.username }}</strong>
                    <strong class="navbar-brand"> | </strong>
                    <a href="{% url 'blog:logout' %}" class="navbar-brand d-flex align-items-center"><strong>Выйти</strong></a>
                {% else %}
                    <a href="{% url 'blog:register' %}" class="navbar-brand d-flex align-items-center"><strong>Регистрация</strong></a>
                    <strong class="navbar-brand"> | </strong>
                    <a href="{% url 'blog:login' %}" class="navbar-brand d-flex align-items-center"><strong>Войти</strong></a>
                {% endif %}
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarHeader"
                        aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
            </div>
        </div>
    </div>
</header>

<div class="container mt-5">
    {% block body %}{% endblock %}
</div>

<footer class="text-muted py-5">
    <div class="container">
        <p class="float-end mb-1">
            <a href="#">Back to top</a>
        </p>
        <p class="mb-1">Album example is © Bootstrap, but please download and customize it for yourself!</p>
        <p class="mb-0">New to Bootstrap? <a href="/">Visit the homepage</a> or read our <a
                href="/docs/5.1/getting-started/introduction/">getting started guide</a>.</p>
    </div>
</footer>


<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.bundle.min.js"></script>

</body>
</html>

blog/templates/blog/create.html
{% extends 'blog/base.html' %}

{% block title %}
<title>{{ title }}</title>
{% endblock %}

{% block body %}
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {% for el in form %}
         <div class="mb-3">
            <div class="form-floating">
                {% if el.label != 'Картинка к посту' and el.label != 'Категория' %}
                    {{ el }}
                    {{ el.label_tag }}
                {% else %}
                    {{ el.label }}
                    {{ el }}
                {% endif %}
            </div>
            {% if el.errors %}
                <ol>
                {% for error in el.errors %}
                    <li><strong class="text-danger">{{ error }}</strong></li>
                {% endfor %}
                </ol>
             {% endif %}
         </div>
    {% endfor %}
    <button type="submit" class="btn btn-primary">Опубликовать</button>
</form>
<h3>{{ error }}</h3>
{% endblock %}c4

blog/templates/blog/index.html
{% extends 'blog/base.html' %}

{% block title %}
<title>{{ title }}</title>
{% endblock %}

{% block body %}
<main>
    <div class="row row-cols-1 row-cols-md-3 g-4">
        {% for post in posts %}
        <div class="col">
            <div class="card h-100">
                <img src="{{ post.image.url }}" class="card-img-top" width="100">
                <div class="card-body">
                    <h5 class="card-title">{{post.author}}. {{ post.title }}</h5>
                    <p class="card-text">{{ post.text|truncatewords:"15" }}</p>
                </div>
                <div class="d-flex card-footer justify-content-between">
                    <small class="text-muted">{{ post.publish_date|timesince }} назад</small>
                    <small class="text-muted"><a class="text-secondary" href="{% url 'blog:show_post' post.slug %}">Читать пост -></a></small>
                </div>
            </div>
        </div>
        {% empty %}
        <h1>Нет ни одного поста!</h1>
        {% endfor %}
    </div>
</main>
{% endblock %}

blog/templates/blog/login.html
{% extends 'blog/base.html' %}

{% block title %}
<title>{{ title }}</title>
{% endblock %}

{% block body %}
<form class="form-signin d-flex justify-content-center" method="post">
    <div class="d-flex flex-column align-items-center w-100">
        <h1 class="h3 mb-3 font-weight-normal">Вход на сайт</h1>
        {% csrf_token %}
        {% for el in form %}
        <div class="mb-3 w-25">
            <div class="form-floating">
                {{ el }}
                {{ el.label_tag }}
            </div>
            {% if el.errors %}
            <ol>
                {% for error in el.errors %}
                <li><strong class="text-danger">{{ error }}</strong></li>
                {% endfor %}
            </ol>
            {% endif %}
        </div>
        {% endfor %}
        <button type="submit" class="btn btn-primary">Войти</button>
    </div>
</form>
{% endblock %}

blog/templates/blog/register.html
{% extends 'blog/base.html' %}

{% block title %}
<title>{{ title }}</title>
{% endblock %}

{% block body %}
<form class="form-signin d-flex justify-content-center" method="post">
    <div class="d-flex flex-column align-items-center w-100">
        <h1 class="h3 mb-3 font-weight-normal">Регистрация</h1>
        {% csrf_token %}
        {% for el in form %}
        <div class="mb-3 w-25">
            <div class="form-floating">
                {{ el }}
                {{ el.label_tag }}
            </div>
            {% if el.errors %}
            <ol>
                {% for error in el.errors %}
                <li><strong class="text-danger">{{ error }}</strong></li>
                {% endfor %}
            </ol>
            {% endif %}
        </div>
        {% endfor %}
        <button type="submit" class="btn btn-primary">Зарегистрироваться</button>
    </div>
</form>
{% endblock %}

blog/templates/blog/show_post.html
{% extends 'blog/base.html' %}

{% block title %}
<title>{{ title }}</title>
{% endblock %}

{% block body %}
    <img src="{{ post.image.url }}" class="card-img-top">
    <p>{{ post.title }}</p>
    <p>{{ post.author }}</p>
    <p>{{ post.publish_date }}</p>
    <p>{{ post.text }}</p>
{% endblock %}